Applied new Bash style guidelines to multi-seat-config scripts.

diff --git a/usr/sbin/oi-lab-multi-seat-config b/usr/sbin/oi-lab-multi-seat-config
--- a/usr/sbin/oi-lab-multi-seat-config
+++ b/usr/sbin/oi-lab-multi-seat-config
@@ -28,12 +28,12 @@
 #set -x
 
 ## Path constants
-MC3SL_DEVICES="/usr/sbin/devices" # shortcut to devices that have already been paired
+MC3SL_DEVICES=/usr/sbin/devices # shortcut to devices that have already been paired
 
 ## Script/function in other file
-FIND_KEYBOARD="find_keyboard" # "find-devices"
-CREATE_WINDOW="create_window" # "window-access"
-WRITE_WINDOW="write_window" # "window-access"
+FIND_KEYBOARD=find_keyboard # "find-devices"
+CREATE_WINDOW=create_window # "window-access"
+WRITE_WINDOW=write_window # "window-access"
 
 ## Macros
 FAKE_DISPLAYS=( :90 :91 ) # display to access fake-seat (secondary card)
@@ -60,120 +60,60 @@ source /usr/share/oi-lab-multi-seat-config/find-devices
 source /usr/share/oi-lab-multi-seat-config/window-access
 
 create_onboard_window () {
-	# Checks if there is a device connected to the onboard card
-	if test "$(cat "/sys$(udevadm info /sys/class/drm/card0 | grep "P:" | cut -d " " -f2)/card0-VGA-1/status")" == "connected"; then
-		# Runs Xorg and creates the window for the onboard card
-		DISPLAY_XORGS[$WINDOW_COUNTER]=:$(($WINDOW_COUNTER+10))
-		export DISPLAY=${DISPLAY_XORGS[$WINDOW_COUNTER]}
+    # Checks if there is a device connected to the onboard card
+    if [[ "$(cat "/sys$(udevadm info /sys/class/drm/card0 | grep "P:" | cut -d " " -f2)/card0-VGA-1/status")" == "connected" ]]
+    then
+        # Runs Xorg and creates the window for the onboard card
+        DISPLAY_XORGS[${WINDOW_COUNTER}]=:$(( WINDOW_COUNTER + 10 ))
+        export DISPLAY=${DISPLAY_XORGS[${WINDOW_COUNTER}]}
 
-#		Xorg ${DISPLAY_XORGS[$WINDOW_COUNTER]} -noreset &
-#		pid=$!
+        ${CREATE_WINDOW} primary
 
-		# Guarantees the Xorg execution
-#		xdpyinfo -display ${DISPLAY_XORGS[$WINDOW_COUNTER]}
-#		EXIT_CODE=$?
-#		N_ATTEMPT=0
-#		while test $EXIT_CODE -ne 0; do
-#			sleep 0.5
-#			xdpyinfo -display ${DISPLAY_XORGS[$WINDOW_COUNTER]}
-#			EXIT_CODE=$?
-#			if ! kill -0 "${pid}" >/dev/null 2>&1; then
-#				Xorg ${DISPLAY_XORGS[$WINDOW_COUNTER]} &
-#				pid=$!
-#			fi
-#
-#			if test $N_ATTEMPT -gt $MAX_ATTEMPTS; then
-#				echo "[Error] Run Xorg ${DISPLAY_XORGS[$WINDOW_COUNTER]} failed."
-#				exit 1
-#	    fi
-#
-#			N_ATTEMPT=$(($N_ATTEMPT+1))
-#		done
-
-		$CREATE_WINDOW primary
-
-		ONBOARD=1
-	else
-		WINDOW_ID_INIT=1
-		WINDOW_COUNTER=1
-	fi
+        ONBOARD=1
+    else
+        WINDOW_ID_INIT=1
+        WINDOW_COUNTER=1
+    fi
 }
 
 create_secondary_card_windows () {
-	#### $1: fake seat display
-	for i in ${OUTPUTS[@]}; do
-		# Display for each output
-		DISPLAY_XORGS[$WINDOW_COUNTER]=${FAKE_DISPLAYS[$1]}
-		export DISPLAY=${FAKE_DISPLAYS[$1]}
+    #### $1: fake seat display
+    for i in ${OUTPUTS[@]}
+    do
+        # Display for each output
+        DISPLAY_XORGS[${WINDOW_COUNTER}]=${FAKE_DISPLAYS[${1}]}
+        export DISPLAY=${FAKE_DISPLAYS[${1}]}
 
-		# Guarantees the Xorg-daemon execution
-#		xdpyinfo -display ${DISPLAY_XORGS[$WINDOW_COUNTER]}
-#		EXIT_CODE=$?
-#		N_ATTEMPT=0
-#		while test $EXIT_CODE -ne 0; do
-#			sleep 0.5
-#			xdpyinfo -display ${DISPLAY_XORGS[$WINDOW_COUNTER]}
-#			EXIT_CODE=$?
-#
-#			if test $N_ATTEMPT -gt $MAX_ATTEMPTS; then
-#				echo "[Error] Communication with Xorg ${DISPLAY_XORGS[$WINDOW_COUNTER]} failed."
-#				exit 1
-#			fi
-#
-#			N_ATTEMPT=$(( N_ATTEMPT + 1 ))
-#		done
-
-		# Run config window to type in this output
-		$CREATE_WINDOW $i
-	done
+        # Run config window to type in this output
+        ${CREATE_WINDOW} ${i}
+    done
 }
 
 configure_devices () {
-	COUNT=0
-	for WINDOW in `seq $WINDOW_ID_INIT $(($WINDOW_COUNTER-1))`; do
-		if test $WINDOW -eq 0; then
-			$WRITE_WINDOW ok $WINDOW
-		else
-			$FIND_KEYBOARD $WINDOW &
-			PID_FIND_DEVICES[$COUNT]=$!
-			COUNT=$(($COUNT+1))
+    COUNT=0
 
-			$WRITE_WINDOW press_key $WINDOW
-		fi
-	done
+    for WINDOW in $(seq ${WINDOW_ID_INIT} $(( WINDOW_COUNTER - 1 )))
+    do
+        if (( WINDOW == 0 ))
+        then
+            ${WRITE_WINDOW} ok ${WINDOW}
+        else
+            ${FIND_KEYBOARD} ${WINDOW} &
+            PID_FIND_DEVICES[$COUNT]=$!
+            COUNT=$(( COUNT + 1 ))
+
+            ${WRITE_WINDOW} press_key ${WINDOW}
+        fi
+    done
 }
 
 kill_jobs () {
-	if test -n "$(ls | grep lock)"; then
-		rm lock*
-	fi
-
-	if test -d "$MC3SL_DEVICES"; then
-		rm -rf $MC3SL_DEVICES/
-	fi
-
-	rm -rf $MC3SL_DEVICES
-
-	pkill -P $$
+    [[ -n $(ls | grep lock) ]] && rm lock*
+    [[ -d ${MC3SL_DEVICES} ]] && rm -rf "${MC3SL_DEVICES}"
+    pkill -P ${$}
 }
 
 ############ BEGIN ############
-
-#xdpyinfo -display $FAKE_DISPLAY
-#EXIT_CODE=$?
-#N_ATTEMPT=0
-#while test $EXIT_CODE -ne 0; do
-#	sleep 0.5
-#	xdpyinfo -display $FAKE_DISPLAY
-#	EXIT_CODE=$?
-#
-#	if test $N_ATTEMPT -gt $MAX_ATTEMPTS; then
-#		echo "[Error] xdpyinfo -display $FAKE_DISPLAY failed."
-#		exit 1
-#	fi
-#
-#	N_ATTEMPT=$(($N_ATTEMPT+1))
-#done
 
 udevadm trigger
 udevadm settle --timeout=10
@@ -189,38 +129,37 @@ N_KEYBOARDS_LISTED=${#KEYBOARDS[@]}
 
 # If there are less connected keyboards than available seat master devices,
 # leave remaining seat master devices unconfigured.
-if test $N_KEYBOARDS_LISTED -lt $N_SEATS_LISTED; then
-	N_CONFIGURABLE_SEATS=${N_KEYBOARDS_LISTED}
-fi
+(( N_KEYBOARDS_LISTED < N_SEATS_LISTED )) && N_CONFIGURABLE_SEATS=${N_KEYBOARDS_LISTED}
 
-if test $N_CONFIGURABLE_SEATS -gt 1; then
-	# If the onboard is connected, it creates a window to write on the screen
-	create_onboard_window
+if (( N_CONFIGURABLE_SEATS > 1 ))
+then
+    # If the onboard is connected, it creates a window to write on the screen
+    create_onboard_window
 
-	# Creates the necessary windows to write on the screen of each output of the secondary card
-	create_secondary_card_windows 0
+    # Creates the necessary windows to write on the screen of each output of the secondary card
+    create_secondary_card_windows 0
+    (( ${#SECONDARY_SEATS[@]} > 2 )) && create_secondary_card_windows 1
 
-	if test ${#SECONDARY_SEATS[@]} -gt 2; then
-		create_secondary_card_windows 1
-	fi
+    # We'll use it to save a shortcut to devices that have already been paired
+    mkdir -p ${MC3SL_DEVICES}
 
-	# We'll use it to save a shortcut to devices that have already been paired
-	mkdir -p $MC3SL_DEVICES
+    # Run configuration script for each seat
+    configure_devices
 
-	# Run configuration script for each seat
-	configure_devices
+    while (( CONFIGURED_SEATS < N_CONFIGURABLE_SEATS ))
+    do
+        wait -n ${PID_FIND_DEVICES[@]}
+        EXIT_CODE=${?}
 
-	while test $CONFIGURED_SEATS -lt $N_CONFIGURABLE_SEATS; do
-		wait -n ${PID_FIND_DEVICES[@]}
-		EXIT_CODE=$?
-
-		if test $EXIT_CODE -eq 0; then
-			CONFIGURED_SEATS=$(( CONFIGURED_SEATS + 1 ))
-		elif test $EXIT_CODE -eq 2; then
-			echo "[Error] Can not configure output: find-devices failed."
-			exit 1
-		fi
-	done
+        if (( EXIT_CODE == 0 ))
+        then
+            CONFIGURED_SEATS=$(( CONFIGURED_SEATS + 1 ))
+        elif (( EXIT_CODE == 2 ))
+        then
+            echo "[Error] Can not configure output: find-devices failed."
+            exit 1
+        fi
+    done
 fi
 
 # Cleans the system by killing all the processes and files it has created
diff --git a/usr/share/oi-lab-multi-seat-config/find-devices b/usr/share/oi-lab-multi-seat-config/find-devices
--- a/usr/share/oi-lab-multi-seat-config/find-devices
+++ b/usr/share/oi-lab-multi-seat-config/find-devices
@@ -24,85 +24,88 @@
 #### Written by: Stephanie Briere Americo - sba16@c3sl.ufpr.br on 2017.
 
 ## Macros
-DEVICES="/usr/sbin/devices" # shortcut to devices that have already been paired
+DEVICES=/usr/sbin/devices # shortcut to devices that have already been paired
 
 ## Script/function in other file
-READ_DEVICES="/usr/sbin/oi-lab-multi-seat-config-read-devices"
-DETECT_KEYBOARDS="/usr/sbin/oi-lab-multi-seat-config-detect-keyboard"
-WRITE_W="write_window" # "window-access"
+READ_DEVICES=/usr/sbin/oi-lab-multi-seat-config-read-devices
+DETECT_KEYBOARDS=/usr/sbin/oi-lab-multi-seat-config-detect-keyboard
+WRITE_W=write_window # "window-access"
 
 ## Variables
 declare -a SEATS_LISTED # save the name of the existing seats
 
 find_keyboard () {
-	fKey=$1 # key that this script should expect to be pressed
-	wNum=$fKey # position in the window control vector
+    fKey=$1 # key that this script should expect to be pressed
+    wNum=$fKey # position in the window control vector
 
-	CREATED=0
-	while test $CREATED -eq 0; do
-		KEYBOARDS=$($DETECT_KEYBOARDS)
+    CREATED=0
+    while (( CREATED == 0 ))
+    do
+        KEYBOARDS=$(${DETECT_KEYBOARDS})
 
-		# List all attached keyboards
-		for i in `ls $DEVICES | grep "\<keyboard"`; do
-			KEYBOARDS=$(sed "s#$i##g" <<< $KEYBOARDS)
-		done
+        # List all attached keyboards
+        for i in $(ls ${DEVICES} | grep "\<keyboard")
+        do
+            KEYBOARDS=$(sed "s#$i##g" <<< ${KEYBOARDS})
+        done
 
-		# If no free (not attached) keyboard is available, you can not proceed
-		if test -z "$KEYBOARDS"; then
-		    echo "[Error] No free keyboards available"
-		    exit 1
-		fi
+        # If no free (not attached) keyboard is available, you can not proceed
+        if [[ -z ${KEYBOARDS} ]]
+        then
+            echo "[Error] No free keyboards available"
+            exit 1
+        fi
 
-		# See if someone presses the expected key
-		PRESSED=$($READ_DEVICES $fKey $KEYBOARDS | grep '^detect' | cut -d'|' -f2)
+        # See if someone presses the expected key
+        PRESSED=$(${READ_DEVICES} ${fKey} ${KEYBOARDS} | grep '^detect' | cut -d'|' -f2)
 
-		# If $READ_DEVICES gets killed the script won't do bad stuff
-		if test -z "$PRESSED"; then
-		    continue
-		fi
+        # If $READ_DEVICES gets killed the script won't do bad stuff
+        [[ -z ${PRESSED} ]] && continue
 
-		# If the key has not yet been processed, continue to wait
-		if test "$PRESSED" = 'timeout'; then
-		    continue
-		fi
+        # If the key has not yet been processed, continue to wait
+        [[ ${PRESSED} == timeout ]] && continue
 
-		# If you got here, then the key was pressed
-		CREATED=1
+        # If you got here, then the key was pressed
+        CREATED=1
 
-		# Creates a link to the keyboard so no one else can use it
-		ln -sf $PRESSED $DEVICES/keyboard_$fKey
+        # Creates a link to the keyboard so no one else can use it
+        ln -sf ${PRESSED} ${DEVICES}/keyboard_${fKey}
 
-		# Check if there's no longer a link to this keyboard
-		for i in `ls $DEVICES | grep "\<keyboard"`; do
-		    if test "$i" != "keyboard_$fKey"; then
-			AUX=$(stat -c %N $DEVICES/$i | cut -d '>' -f2 | cut -d "'" -f2)
+        # Check if there's no longer a link to this keyboard
+        for i in $(ls ${DEVICES} | grep "\<keyboard")
+        do
+            if [[ ${i} != "keyboard_${fKey}" ]]
+            then
+                AUX=$(stat -c %N ${DEVICES}/${i} | cut -d '>' -f2 | cut -d "'" -f2)
 
-			if test "$AUX" = "$PRESSED"; then
-			    # Keyboard link already exists, try again
-			    rm -f $DEVICES/keyboard_$fKey
-			    CREATED=0
-			fi
-		    fi
-		done
-	done
+                if [[ ${AUX} == ${PRESSED} ]]
+                then
+                    # Keyboard link already exists, try again
+                    rm -f ${DEVICES}/keyboard_${fKey}
+                    CREATED=0
+                fi
+            fi
+        done
+    done
 
-	# Find device address
-	SYS_DEV=/sys$(udevadm info $PRESSED | grep 'P:' | cut -d ' ' -f2- | sed -r 's/event.*$//g')
+    # Find device address
+    SYS_DEV=/sys$(udevadm info ${PRESSED} | grep 'P:' | cut -d ' ' -f2- | sed -r 's/event.*$//g')
 
-	if test -n "$SYS_DEV"; then
-		# Get parent USB hub syspath
-		PARENT_SYSPATH=$(echo $SYS_DEV | cut -d/ -f1-7)
+    if [[ -n ${SYS_DEV} ]]
+    then
+        # Get parent USB hub syspath
+        PARENT_SYSPATH=$(echo ${SYS_DEV} | cut -d/ -f1-7)
 
-		$WRITE_W ok $wNum
+        ${WRITE_W} ok ${wNum}
 
-		# Attach devices to a new seat
-		loginctl attach ${SEAT_NAMES[$((fKey-1))]} ${SECONDARY_SEATS[$((fKey-1))]} $PARENT_SYSPATH
-		udevadm control --reload-rules
-		udevadm trigger
+        # Attach devices to a new seat
+        loginctl attach ${SEAT_NAMES[$(( fKey - 1 ))]} ${SECONDARY_SEATS[$(( fKey - 1 ))]} ${PARENT_SYSPATH}
+        udevadm control --reload-rules
+        udevadm trigger
 
-		exit 0
-	else
-		echo "[Error] Can not find keyboard!"
-		exit 2
-	fi
+        exit 0
+    else
+        echo "[Error] Can not find keyboard!"
+        exit 2
+    fi
 }
diff --git a/usr/share/oi-lab-multi-seat-config/window-access b/usr/share/oi-lab-multi-seat-config/window-access
--- a/usr/share/oi-lab-multi-seat-config/window-access
+++ b/usr/share/oi-lab-multi-seat-config/window-access
@@ -26,73 +26,66 @@
 #### Modified by: Laércio de Sousa - laerciosousa@sme-mogidascruzes.sp.gov.br on 2018.
 
 ## Script/function in other file
-NEW_WINDOW="oi-lab-multi-seat-config-window" # it receives as parameter <RESOLUTION>x<X_Initial>+<Y_Inicial>
-WRITE_MESSAGE="oi-lab-multi-seat-config-message" # it receives as parameter <ID_WINDOW> <Message>
+NEW_WINDOW=oi-lab-multi-seat-config-window # it receives as parameter <RESOLUTION>x<X_Initial>+<Y_Inicial>
+WRITE_MESSAGE=oi-lab-multi-seat-config-message # it receives as parameter <ID_WINDOW> <Message>
 MAX_ATTEMPTS=100
 
 get_output_geometry () {
-	xrandr -display ${DISPLAY_XORGS[$WINDOW_COUNTER]} | grep $1 | grep -Po '\d+x\d+\+\d+\+\d+'
+    xrandr -display ${DISPLAY_XORGS[$WINDOW_COUNTER]} | grep ${1} | grep -Po '\d+x\d+\+\d+\+\d+'
 }
 
 create_window () {
-	#### Description: Create a window in a specific display.
-	#### ID_WINDOWS and WINDOW_COUNTER are declared in "multiseat-controller".
-        #### $1: target RandR output
+    #### Description: Create a window in a specific display.
+    #### ID_WINDOWS and WINDOW_COUNTER are declared in "multiseat-controller".
+    #### $1: target RandR output
 
-	# Try to access Xorg
-#	xdpyinfo -display ${DISPLAY_XORGS[$WINDOW_COUNTER]}
-#	EXIT_CODE=$?
-#	while test $EXIT_CODE -ne 0; do
-#		sleep 0.5
-#		xdpyinfo -display ${DISPLAY_XORGS[$WINDOW_COUNTER]}
-#		EXIT_CODE=$?
-#	done
+    # Creates a new window for writing on this output
+    WINDOW_NAME=w$(( WINDOW_COUNTER + 1 ))
+    WINDOW_GEOMETRY=$(get_output_geometry ${1})
+    ${NEW_WINDOW} ${WINDOW_GEOMETRY} ${WINDOW_NAME} &
 
-	# Creates a new window for writing on this output
-	WINDOW_NAME=w$(($WINDOW_COUNTER+1))
-        WINDOW_GEOMETRY=$(get_output_geometry $1)
-	$NEW_WINDOW $WINDOW_GEOMETRY $WINDOW_NAME &
+    # Try to access the window
+    xwininfo -name ${WINDOW_NAME}
+    EXIT_CODE=${?}
+    N_ATTEMPT=0
+    while (( EXIT_CODE != 0 ))
+    do
+        sleep 0.5
+        xwininfo -name ${WINDOW_NAME}
+        EXIT_CODE=${?}
 
-	# Try to access the window
-	xwininfo -name $WINDOW_NAME
-	EXIT_CODE=$?
-	N_ATTEMPT=0
-	while test $EXIT_CODE -ne 0; do
-		sleep 0.5
-		xwininfo -name $WINDOW_NAME
-		EXIT_CODE=$?
+        if (( N_ATTEMPT > MAX_ATTEMPTS ))
+        then
+            echo "[Error] Failed to create window ${WINDOW_NAME}."
+            exit 1
+        fi
 
-		if test $N_ATTEMPT -gt $MAX_ATTEMPTS; then
-			echo "[Error] Failed to create window $WINDOW_NAME."
-			exit 1
-	    fi
+        N_ATTEMPT=$(( N_ATTEMPT + 1 ))
+    done
 
-		N_ATTEMPT=$(( N_ATTEMPT + 1 ))
-	done
+    # Get the window id
+    ID_WINDOWS[${WINDOW_COUNTER}]=$(xwininfo -name ${WINDOW_NAME} | grep "Window id" | cut -d ' ' -f4)
 
-	# Get the window id
-	ID_WINDOWS[$WINDOW_COUNTER]=$(xwininfo -name $WINDOW_NAME | grep "Window id" | cut -d ' ' -f4)
+    write_window wait_load ${WINDOW_COUNTER}
 
-	write_window wait_load $WINDOW_COUNTER
-
-	# Increases the number of windows
-	WINDOW_COUNTER=$(($WINDOW_COUNTER+1))
+    # Increases the number of windows
+    WINDOW_COUNTER=$(( WINDOW_COUNTER + 1 ))
 }
 
-write_window() {
-	#### Description: Writes in a specific window on a particular display.
-	#### Parameters: $1 - message to be written; $2 - display to be used.
-	#### DISPLAY_XORGS and ID_WINDOWS are declared in "multiseat-controller".
+write_window () {
+    #### Description: Writes in a specific window on a particular display.
+    #### Parameters: $1 - message to be written; $2 - display to be used.
+    #### DISPLAY_XORGS and ID_WINDOWS are declared in "multiseat-controller".
 
-	export DISPLAY=${DISPLAY_XORGS[$2]}
-	case $1 in
-		ok)
-			$WRITE_MESSAGE ${ID_WINDOWS[$2]} "Terminal pronto para uso!" "Aguarde a configuração dos terminais restantes..." ;;
-		wait_load)
-			$WRITE_MESSAGE ${ID_WINDOWS[$2]} "Aguarde..." ;;
-		press_key)
-			$WRITE_MESSAGE ${ID_WINDOWS[$2]} "Pressione a tecla F$2" "no teclado em frente a este monitor..." ;;
-		press_mouse)
-			$WRITE_MESSAGE ${ID_WINDOWS[$2]} "Pressione o botão esquerdo do mouse" "em frente a este monitor..." ;;
-	esac
+    export DISPLAY=${DISPLAY_XORGS[${2}]}
+    case ${1} in
+        ok)
+            ${WRITE_MESSAGE} ${ID_WINDOWS[${2}]} "Terminal pronto para uso!" "Aguarde a configuração dos terminais restantes..." ;;
+        wait_load)
+            ${WRITE_MESSAGE} ${ID_WINDOWS[${2}]} "Aguarde..." ;;
+        press_key)
+            ${WRITE_MESSAGE} ${ID_WINDOWS[${2}]} "Pressione a tecla F${2}" "no teclado em frente a este monitor..." ;;
+        press_mouse)
+            ${WRITE_MESSAGE} ${ID_WINDOWS[${2}]} "Pressione o botão esquerdo do mouse" "em frente a este monitor..." ;;
+    esac
 }
